name: 'Publish to NPM'
description: Github action to publish to NPM

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ github.head_ref }}
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'yarn'
    - shell: bash
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
        yarn install
        git status && git add . && git commit -m "fix: install dependencies" || echo "Nothing to commit"
        yarn release-it