name: 'Interaction Test'
description: Github action to run interaction test

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'yarn'
    - shell: bash
      run: |
        npx playwright install-deps
        yarn install
        yarn add concurrently
        yarn concurrently -k -s first -n \"SB,TEST\" -c \"magenta,blue\" "yarn storybook:build --quiet && npx http-server storybook-static --port 6006 --silent" "wait-on tcp:6006 && yarn storybook:test:cross-browser"